### ISSUE TITLE
Failure writing to S3

### ISSUE THREAD

**Issue by kstaken** [terascope/file-assets#230]
Getting this error sending some data to S3.  Points to some kind of issue in S3Batcher. It doesn't fail on every slice.

```
TSError: Invalid data source, must be an object, got "Array"
        at pRetry (/Users/kstaken/projects/opensource/teraslice/packages/utils/dist/src/promises.js:55:21)
        at new DataEntity (/Users/kstaken/projects/opensource/teraslice/assets/657739bb3e8df536adaa49b2ec9d5a6f52b1537c/node_modules/@terascope/utils/dist/src/entities/data-entity.js:33:19)
        at Function.make (/Users/kstaken/projects/opensource/teraslice/assets/657739bb3e8df536adaa49b2ec9d5a6f52b1537c/node_modules/@terascope/utils/dist/src/entities/data-entity.js:44:16)
        at input.map (/Users/kstaken/projects/opensource/teraslice/assets/657739bb3e8df536adaa49b2ec9d5a6f52b1537c/node_modules/@terascope/utils/dist/src/entities/data-entity.js:58:44)
        at Array.map (<anonymous>)
        at Function.makeArray (/Users/kstaken/projects/opensource/teraslice/assets/657739bb3e8df536adaa49b2ec9d5a6f52b1537c/node_modules/@terascope/utils/dist/src/entities/data-entity.js:58:22)
        at S3Batcher.handle (/Users/kstaken/projects/opensource/teraslice/assets/657739bb3e8df536adaa49b2ec9d5a6f52b1537c/node_modules/@terascope/job-components/dist/src/operations/batch-processor.js:14:35)
```

**Comment by kstaken** [comment]
This is fixed.
