### ISSUE TITLE
Fix TLS encrypted S3 client connection issue

### ISSUE THREAD

**Issue by godber** [terascope/file-assets#960]
When trying to write to S3 the `s3_sender` using Terasice `v1.1.0` it now fails with the following error:

```
[2024-03-21T22:24:26.858Z]  INFO: teraslice/7 on ts-wkr-dg-to-s3-s3-2-6-1-a9b83ac3-3929-6cc55974d-5kwpg: creating connection for s3 (assignment=worker)
[2024-03-21T22:24:26.859Z]  INFO: teraslice/7 on ts-wkr-dg-to-s3-s3-2-6-1-a9b83ac3-3929-6cc55974d-5kwpg: Using S3 endpoint: https://s3.example.com/ (assignment=worker)
[2024-03-21T22:24:26.977Z]  INFO: teraslice/7 on ts-wkr-dg-to-s3-s3-2-6-1-a9b83ac3-3929-6cc55974d-5kwpg: [FINISH] "s3_exporter" operation initialize, took 119ms (assignment=worker, module=worker_context, worker_id=Di6ldIU2, ex_id=322cdce2-e2e5-4a12-ae0d-79382e9739b0, job_id=a9b83ac3-3929-4cb6-97bd-299e44b41051)
[2024-03-21T22:24:26.977Z] ERROR: teraslice/7 on ts-wkr-dg-to-s3-s3-2-6-1-a9b83ac3-3929-6cc55974d-5kwpg: Teraslice Worker shutting down due to failure! (assignment=worker, err.code=UNABLE_TO_GET_ISSUER_CERT_LOCALLY)
    TSError: Failure to setup bucket /ts-v1-1-0-nodev18-19-1-44662-1711058774962-test1-dg-to-s3, caused by Error: unable to get local issuer certificate
        at S3Sender2.ensureBucket (/app/assets/048a1106719a9422910df655860bdc29d13b44ed/index.js:124543:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async S3SenderAPI.create (/app/assets/048a1106719a9422910df655860bdc29d13b44ed/index.js:125584:5)
        at async Object.create (/app/assets/048a1106719a9422910df655860bdc29d13b44ed/index.js:51941:40)
        at async S3Batcher.initialize (/app/assets/048a1106719a9422910df655860bdc29d13b44ed/index.js:125408:16)
        at async /app/source/packages/job-components/dist/src/execution-context/base.js:61:17
        at async /app/source/node_modules/p-map/index.js:57:22
[2024-03-21T22:24:27.079Z]  WARN: teraslice/7 on ts-wkr-dg-to-s3-s3-2-6-1-a9b83ac3-3929-6cc55974d-5kwpg: worker shutdown was called for execution 322cdce2-e2e5-4a12-ae0d-79382e9739b0 due to event: error (assignment=worker, module=worker, worker_id=Di6ldIU2, ex_id=322cdce2-e2e5-4a12-ae0d-79382e9739b0, job_id=a9b83ac3-3929-4cb6-97bd-299e44b41051)
```

This should be reproduced locally and fixed.

**Comment by godber** [comment]
After Peter and Joseph's work on Friday to isolate this to changes in `createS3Client.ts` that have just now made it in to Teraslice, I spent some time looking at whats going on.  The issue was introduced into Teraslice in [this commit](https://github.com/terascope/teraslice/commit/f49196180febcb181baaceef06efd2f744ce6a72#diff-86573b3a51d53d88cacf65eeb1274fbe52a0a3ba6000081d5a7f6269f26d0e17R30) where `file-asset-apis` was updated from `^0.10.1` to `^0.12.0`.

I spent some time playing with it and this has gotten sufficiently complex:

https://github.com/terascope/file-assets/blob/c79c25bdf6a82c91c697160bc7c267b6dcfb8254/packages/file-asset-apis/src/s3/createS3Client.ts#L33-L82

I don't think the `certs` are getting added to the final config that actually creates the client.  I think the code highlighted above should be refactored out into it's own function (all it does is munge configs) and unit tested.  This will allow for clearer understanding of that the input/output types are and REAL test coverage of this code.
